### ISSUE TITLE
Adding gem breaks stylesheet_link_tag in my app

### ISSUE THREAD

**Issue by vollnhals** [westonganger/rails_local_analytics#15]
After I added the gem to my app. Rails can no longer render the application stylesheet tag.

```
    = stylesheet_link_tag "4/application", :media => "all"
```

Instead an exception is raised

```
Sprockets::ArgumentError - link_tree argument must be a directory:
  app/views/layouts/4/devise.html.haml:12
  config/initializers/rack_timeout.rb:21:in `call'
  config/initializers/rack_sendfile.rb:7:in `call'
```

This is because rails_local_analytics has an asset config manifest that references non existing directories

```
⋊> ~/W/gomus on local-analytics ⨯ cat /Users/lion/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rails_local_analytics-0.2.2/app/assets/config/rails_local_analytics_manifest.js     
//= link_tree ../images/rails_local_analytics
//= link_directory ../stylesheets/rails_local_analytics .css
//= link_directory ../javascripts/rails_local_analytics .js
```

But there is only the stylesheets directory

```
⋊> ~/W/gomus on local-analytics ⨯ ls /Users/lion/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rails_local_analytics-0.2.2/app/assets/                                               
config/      stylesheets/
```

When I remove the other lines from assets/config/rails_local_analytics_manifest.js then my app works again

**Comment by westonganger** [comment]
Thanks for your investigation that helps so much.

Ok so I think the reason this was not caught in development or CI is because of this line in the gemspec:

```
spec.files = Dir["{app,config,db,lib,public}/**/*", "LICENSE", "Rakefile", "README.md"]
```

I suspect that it removes the folders with hidden files (example `app/assets/images/` only contains a `.keep` file)

I'll try to get this fixed right away.

**Comment by westonganger** [comment]
Do you have the full stack trace? For one solution im hoping the issue only exists in `link_tree` and not in `link_directory`

**Comment by westonganger** [comment]
Can you try adding this to your gemfile and confirm that it solves the issue for you.

gem "rails_local_analytics", git: "https://github.com/westonganger/rails_local_analytics", branch: "fix-sprockets-manifest-issue"

**Comment by westonganger** [comment]
v0.2.3 is now released which contains the fix for this.
